FROM node:18.18-alpine AS base

# Install libc6-compat for compatibility with certain Node.js native modules
RUN apk add --no-cache libc6-compat

# Install pnpm globally
RUN npm install -g pnpm

WORKDIR /app

# Install dependencies
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm install; \
  elif [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Expose port for development
EXPOSE 3080

# Set environment variables for development
ENV NODE_ENV=development
ENV PORT=3080
ENV HOSTNAME="0.0.0.0"

# Start the Next.js development server
CMD ["pnpm", "dev"]
